// Code generated by MockGen. DO NOT EDIT.
// Source: timegenerator.go

// Package timegenerator_mock is a generated GoMock package.
package timegenerator_mock

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockTimeGenInterface is a mock of TimeGenInterface interface.
type MockTimeGenInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTimeGenInterfaceMockRecorder
}

// MockTimeGenInterfaceMockRecorder is the mock recorder for MockTimeGenInterface.
type MockTimeGenInterfaceMockRecorder struct {
	mock *MockTimeGenInterface
}

// NewMockTimeGenInterface creates a new mock instance.
func NewMockTimeGenInterface(ctrl *gomock.Controller) *MockTimeGenInterface {
	mock := &MockTimeGenInterface{ctrl: ctrl}
	mock.recorder = &MockTimeGenInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimeGenInterface) EXPECT() *MockTimeGenInterfaceMockRecorder {
	return m.recorder
}

// Now mocks base method.
func (m *MockTimeGenInterface) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockTimeGenInterfaceMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockTimeGenInterface)(nil).Now))
}
